title: "Tal Sitton - Software Developer"
description: "Welcome to my portfolio! I'm Tal Sitton, a passionate software developer with a focus on full-stack applications and innovative solutions. Explore my projects to see how I blend creativity and technology to build impactful solutions."
remote_theme: "brianmaierjr/long-haul"
baseurl: ""
url: "https://code.sitton.dev"
author: 
  name: "Tal Sitton"

navigation:
    - title: Projects
      url: /index.html#Projects