remote_theme: tuur29/pages-themes-cayman
title: Tal Sitton - Software Developer
description: "A passionate software developer focusing on full-stack applications and innovative solutions"
markdown: kramdown

color:
  gradient_left: "#74D680"
  gradient_right: "#378B29"
  
darkmode: true
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css

author: 
  name: "Tal Sitton"
