title: "Tal Sitton's Official Site"
description: "Personal site of Tal Sitton, a software developer passionate about creating useful applications."
theme: jekyll-theme-cayman
url: "https://code.sitton.dev"
author: 
  name: "Tal Sitton"
